lr: [2.5e-4]
cond_dim: [128]
channels:
  - [64,128,256]

yaw_w: [0.5]
goal_w: [0.5]
path_w: [0.5]
num_cond: [2]
smooth_w: [0.8]

path_t_thresh: [0.3]

timesteps: [200]
beta_schedule: ["scaled_linear"]
batch_size: [256]
epochs: [100]
weight_decay: [0.5e-4]

dataset:
  - 
    - csv_path: "V2_01_easy.csv"
      pos_columns: [' p_RS_R_x [m]',' p_RS_R_y [m]',' p_RS_R_z [m]']
      quat_columns: [' q_RS_x []',' q_RS_y []',' q_RS_z []',' q_RS_w []']
      time_column: "#timestamp"

    - csv_path: "V2_02_medium.csv"
      pos_columns: [' p_RS_R_x [m]',' p_RS_R_y [m]',' p_RS_R_z [m]']
      quat_columns: [' q_RS_x []',' q_RS_y []',' q_RS_z []',' q_RS_w []']
      time_column: "#timestamp"

    - csv_path: "V2_03_difficult.csv"
      pos_columns: [' p_RS_R_x [m]',' p_RS_R_y [m]',' p_RS_R_z [m]']
      quat_columns: [' q_RS_x []',' q_RS_y []',' q_RS_z []',' q_RS_w []']
      time_column: "#timestamp"
