lr: [2e-4]
emb_dim: [128]
base_channel: [64]
num_levels: [2]

yaw_w: [0.0]
goal_w: [0.5]
path_w: [0.5]
num_cond: [2]
smooth_w: [50]
recon_w: [0.9]

path_t_thresh: [0.2]

timesteps: [500]
beta_schedule: ["scaled_linear"]
batch_size: [256]
epochs: [100]
weight_decay: [1e-4]

# dataset:
#   - 
#     - csv_path: "V2_01_easy.csv"
#       pos_columns: [' p_RS_R_x [m]',' p_RS_R_y [m]',' p_RS_R_z [m]']
#       quat_columns: [' q_RS_x []',' q_RS_y []',' q_RS_z []',' q_RS_w []']
#       time_column: "#timestamp"

#     - csv_path: "V2_02_medium.csv"
#       pos_columns: [' p_RS_R_x [m]',' p_RS_R_y [m]',' p_RS_R_z [m]']
#       quat_columns: [' q_RS_x []',' q_RS_y []',' q_RS_z []',' q_RS_w []']
#       time_column: "#timestamp"

#     - csv_path: "V2_03_difficult.csv"
#       pos_columns: [' p_RS_R_x [m]',' p_RS_R_y [m]',' p_RS_R_z [m]']
#       quat_columns: [' q_RS_x []',' q_RS_y []',' q_RS_z []',' q_RS_w []']
#       time_column: "#timestamp"


# Параметры траектории и нормализации
dataset_params:
  context_points: 5
  target_points: 21
  target_offset_points: 3
  goal_offset_points: 50
  target_freq: 10
  stride_points: 3
  time_horizon_scale: 2.1
  augment: true

# Список файлов и срезы (start/end в индексах строк)
data_sources:
  - path: /home/ivan/Desktop/sets/factory2.txt
    start: 2000
    end: null # null означает до конца файла